import About from "./landingPage/About";
import Contact from "./landingPage/Contact";
import Gallery from "./landingPage/Gallery";
import Hero from "./landingPage/Hero";
import Products from "./landingPage/Products";
import Navbar from "./Navbar";
import NavNormal from "./NavNormal";
import Footer from "./Footer";
import Description from "./AboutPage/Description";
import Services from "./AboutPage/Services";
import ProductDesc from "./productPage/ProductDesc";
import HeadingPage from "./HeadingPage";
import HeroImage from "./HeroImage";
import ProductCard from "./landingPage/ProductCard";
import SectionTitle from "./landingPage/SectionTitle";
import DropdownCard from "./productPage/DropdownCard";
import GalleryCard from "./galleryPage/GalleryCard";
import GallerySection from "./galleryPage/GallerySection";
import ImageModal from "./galleryPage/ImageModal";
import HeadingMap from "./contactPage/HeadingMap";
import ContactList from "./contactPage/ContactList";

export { Navbar, NavNormal, Footer, About, Contact, Gallery, Hero, Products, Description, Services, ProductDesc, HeadingPage, HeroImage, ProductCard, SectionTitle, DropdownCard, GalleryCard, GallerySection, ImageModal, HeadingMap, ContactList };
